development:
  adapter: postgresql
  encoding: utf8
  database: stock_development
  pool: 5
  host: localhost
  username: ENV["STOCK_USER"]
  password: ENV["STOCK_PASS"]

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: stock_test
  pool: 5
  host: localhost
  username: ENV["STOCK_USER"]
  password: ENV["STOCK_PASS"]

production:
  adapter: postgresql
  encoding: utf8
  database: stock_production
  pool: 5
  host: localhost
  username: ENV["STOCK_USER"]
  password: ENV["STOCK_PASS"]

cucumber:
  <<: *TEST
