development:
  adapter: postgresql
  encoding: utf8
  database: stock_development
  pool: 5
  host: localhost
  username: postgres
  password: test

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: stock_test
  pool: 5
  host: localhost
  username: postgres
  password: test

production:
  adapter: postgresql
  encoding: utf8
  database: stock_production
  pool: 5
  host: localhost
  username: postgres
  password: test

cucumber:
  <<: *TEST
